# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 20
  - name: Slide
    url: slide/
    weight: 30
  - name: Slide-menu
    url: slide-menu/
    weight: 40
